networks:
  soulfriend-network:
    driver: bridge
services:
  nginx:
    depends_on:
    - soulfriend-app
    image: nginx:alpine
    networks:
    - soulfriend-network
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/nginx/ssl
  redis:
    image: redis:7-alpine
    networks:
    - soulfriend-network
    ports:
    - 6379:6379
    restart: unless-stopped
    volumes:
    - redis-data:/data
  soulfriend-app:
    build: .
    environment:
    - STREAMLIT_SERVER_PORT=8501
    - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
    - soulfriend-network
    ports:
    - 8501:8501
    - 8502:8502
    - 8503:8503
    - 8504:8504
    - 8505:8505
    - 8506:8506
    - 8507:8507
    restart: unless-stopped
    volumes:
    - ./data:/app/data
version: '3.8'
volumes:
  redis-data: {}
