networks:
  soulfriend-network:
    attachable: true
    driver: overlay
services:
  nginx:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    image: nginx:alpine
    networks:
    - soulfriend-network
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/nginx/ssl
  redis:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    image: redis:7-alpine
    networks:
    - soulfriend-network
    volumes:
    - redis-data:/data
  soulfriend-app:
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
    - STREAMLIT_SERVER_PORT=8501
    - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    - REDIS_URL=redis://redis:6379
    networks:
    - soulfriend-network
    volumes:
    - ./data:/app/data
version: '3.8'
volumes:
  redis-data: {}
