# Template for Streamlit Cloud Secrets
# Copy this to your Streamlit Cloud app secrets section

[gemini]
api_key = "YOUR_GEMINI_API_KEY_HERE"

# Instructions:
# 1. Go to https://share.streamlit.io
# 2. Select your app
# 3. Go to Settings > Secrets
# 4. Add the above content with your actual API key
